"""baseline_schema

Revision ID: 06fd0c29fcb8
Revises: 
Create Date: 2026-03-05 18:59:15.748209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fd0c29fcb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identities_author_id'), 'identities', ['author_id'], unique=True)
    op.create_table('transparency_log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('entry_hash', sa.LargeBinary(), nullable=False),
    sa.Column('leaf_index', sa.Integer(), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transparency_log_entries_content_id'), 'transparency_log_entries', ['content_id'], unique=False)
    op.create_table('transparency_log_roots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tree_size', sa.Integer(), nullable=False),
    sa.Column('root_hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('content_hash_sha256', sa.LargeBinary(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('signed_storage_key', sa.String(), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_author_id'), 'videos', ['author_id'], unique=False)
    op.create_index(op.f('ix_videos_content_id'), 'videos', ['content_id'], unique=True)
    op.create_table('embedding_recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('rs_n', sa.Integer(), nullable=False),
    sa.Column('rs_k', sa.Integer(), nullable=False),
    sa.Column('pilot_hash_48', sa.LargeBinary(), nullable=False),
    sa.Column('prng_seeds_json', sa.Text(), nullable=False),
    sa.Column('band_configs_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['videos.content_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_recipes_content_id'), 'embedding_recipes', ['content_id'], unique=False)
    op.create_table('pilot_tone_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('pilot_hash_48', sa.LargeBinary(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['videos.content_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilot_tone_index_content_id'), 'pilot_tone_index', ['content_id'], unique=False)
    op.create_table('video_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_time_s', sa.Float(), nullable=False),
    sa.Column('end_time_s', sa.Float(), nullable=False),
    sa.Column('rs_codeword', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['videos.content_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_segments_content_id'), 'video_segments', ['content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_segments_content_id'), table_name='video_segments')
    op.drop_table('video_segments')
    op.drop_index(op.f('ix_pilot_tone_index_content_id'), table_name='pilot_tone_index')
    op.drop_table('pilot_tone_index')
    op.drop_index(op.f('ix_embedding_recipes_content_id'), table_name='embedding_recipes')
    op.drop_table('embedding_recipes')
    op.drop_index(op.f('ix_videos_content_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_author_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_table('transparency_log_roots')
    op.drop_index(op.f('ix_transparency_log_entries_content_id'), table_name='transparency_log_entries')
    op.drop_table('transparency_log_entries')
    op.drop_index(op.f('ix_identities_author_id'), table_name='identities')
    op.drop_table('identities')
    # ### end Alembic commands ###
