"""End-to-end regression tests for the chunked parallel video signing pipeline.

Each test drives the full sign-then-verify roundtrip on a synthetic video
generated by ffmpeg's ``testsrc2`` source. All tests are marked ``polygon``
and ``slow`` — they are excluded from the default CI tier and run in the
polygon suite via ``make polygon``.

Covered behaviours:

* Chunked signing produces a verifiable WID.
* Both chunked and sequential encode paths yield ``Verdict.VERIFIED``.
* Guard bands (``CHUNK_GUARD_SEGMENTS=1``) do not cause a regression compared
  to ``GUARD=0``.
* ``validate_chunks`` detects a missing chunk output file.
* A short clip (90 s) that still clears the RS minimum signs and verifies
  through the chunked path.
"""
from __future__ import annotations

import tempfile
from pathlib import Path
from types import SimpleNamespace

import pytest

from kernel_backend.core.domain.chunk import ChunkResult
from kernel_backend.core.domain.identity import Certificate
from kernel_backend.core.domain.verification import Verdict
from kernel_backend.core.services.chunk_assembler import validate_chunks
from kernel_backend.core.services.chunk_planner import plan_chunks
from kernel_backend.core.services.crypto_service import generate_keypair
from kernel_backend.core.services.signing_service import sign_video
from kernel_backend.core.services.verification_service import VerificationService
from kernel_backend.infrastructure.media.media_service import MediaService
from tests.helpers.fakes import FakeRegistry, FakeStorage


PEPPER = b"polygon-chunk-pepper-padded-32b!"


def _make_cert(public_key_pem: str) -> Certificate:
    return Certificate(
        author_id="polygon-chunk-author",
        name="Polygon Chunk Test",
        institution="Test Org",
        public_key_pem=public_key_pem,
        created_at="2026-04-15T00:00:00+00:00",
    )


def _override_settings(monkeypatch, **overrides):
    """Patch ``get_settings`` in the signing module with field overrides.

    The signing module imports ``get_settings`` by name, so patching that
    binding is sufficient; the worker subprocesses receive the resolved chunk
    manifest and do not consult settings themselves.
    """
    from kernel_backend.config import get_settings
    import kernel_backend.core.services.signing_service as ss

    base = get_settings()
    patched = base.model_copy(update=overrides)
    monkeypatch.setattr(ss, "get_settings", lambda: patched)
    return patched


async def _sign_and_verify(source: Path):
    """Sign ``source`` via :func:`sign_video` and verify the result. Returns
    the :class:`VerificationResult`.
    """
    private_pem, public_pem = generate_keypair()
    cert = _make_cert(public_pem)
    storage = FakeStorage()
    registry = FakeRegistry()
    media = MediaService()

    sign_result = await sign_video(
        media_path=source,
        certificate=cert,
        private_key_pem=private_pem,
        storage=storage,
        registry=registry,
        pepper=PEPPER,
        media=media,
        output_crf=0,
    )

    with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as tmp:
        signed_path = Path(tmp.name)
    try:
        signed_path.write_bytes(await storage.get(sign_result.signed_media_key))
        service = VerificationService()
        return await service.verify(
            media_path=signed_path,
            media=media,
            storage=storage,
            registry=registry,
            pepper=PEPPER,
        )
    finally:
        signed_path.unlink(missing_ok=True)


@pytest.mark.polygon
@pytest.mark.slow
async def test_chunked_video_produces_verifiable_wid(
    monkeypatch, chunked_test_video: Path
) -> None:
    _override_settings(
        monkeypatch,
        CHUNK_WORKERS=2,
        CHUNK_GUARD_SEGMENTS=1,
        CHUNK_MIN_PAYLOAD_SEGMENTS=4,
    )
    result = await _sign_and_verify(chunked_test_video)
    assert result.verdict == Verdict.VERIFIED, (
        f"Expected VERIFIED but got {result.verdict} (reason={result.red_reason})"
    )
    assert result.wid_match is True
    assert result.signature_valid is True


@pytest.mark.polygon
@pytest.mark.slow
async def test_chunked_matches_sequential(
    monkeypatch, chunked_test_video: Path
) -> None:
    """Chunked and sequential encodes must both yield a verifiable signed file.

    content_id differs across signings so the two WIDs cannot be compared
    directly — the contract here is that each path independently produces a
    VERIFIED verdict.
    """
    _override_settings(
        monkeypatch,
        CHUNK_WORKERS=2,
        CHUNK_GUARD_SEGMENTS=1,
        CHUNK_MIN_PAYLOAD_SEGMENTS=4,
    )
    chunked = await _sign_and_verify(chunked_test_video)

    # CHUNK_WORKERS=1 collapses plan_chunks to a single chunk, which routes
    # through the sequential fallback helper.
    _override_settings(
        monkeypatch,
        CHUNK_WORKERS=1,
        CHUNK_GUARD_SEGMENTS=1,
        CHUNK_MIN_PAYLOAD_SEGMENTS=4,
    )
    sequential = await _sign_and_verify(chunked_test_video)

    assert chunked.verdict == Verdict.VERIFIED
    assert chunked.wid_match is True
    assert sequential.verdict == Verdict.VERIFIED
    assert sequential.wid_match is True


@pytest.mark.polygon
@pytest.mark.slow
async def test_chunked_guard_bands_no_quality_regression(
    monkeypatch, chunked_test_video: Path
) -> None:
    """GUARD=0 and GUARD=1 must both produce VERIFIED — guards only add
    encoder warm-up context, they must never make verification worse."""
    _override_settings(
        monkeypatch,
        CHUNK_WORKERS=2,
        CHUNK_GUARD_SEGMENTS=0,
        CHUNK_MIN_PAYLOAD_SEGMENTS=4,
    )
    no_guard = await _sign_and_verify(chunked_test_video)

    _override_settings(
        monkeypatch,
        CHUNK_WORKERS=2,
        CHUNK_GUARD_SEGMENTS=1,
        CHUNK_MIN_PAYLOAD_SEGMENTS=4,
    )
    with_guard = await _sign_and_verify(chunked_test_video)

    assert no_guard.verdict == Verdict.VERIFIED, (
        f"GUARD=0 unexpectedly not VERIFIED: {no_guard.verdict} "
        f"(reason={no_guard.red_reason})"
    )
    assert with_guard.verdict == Verdict.VERIFIED, (
        f"GUARD=1 unexpectedly not VERIFIED: {with_guard.verdict} "
        f"(reason={with_guard.red_reason})"
    )


@pytest.mark.polygon
def test_chunk_count_validation_catches_missing(tmp_path: Path) -> None:
    """Deleting one chunk output before validate_chunks must surface as
    ``is_valid=False`` with a ``missing``-worded error."""
    manifest = plan_chunks(
        total_segments=20,
        segment_duration_s=5.0,
        n_workers=4,
        guard_segments=1,
        min_payload_segments=4,
    )

    results: list[ChunkResult] = []
    for spec in manifest.chunks:
        out = tmp_path / f"chunk_{spec.chunk_id:04d}.mp4"
        out.write_bytes(b"fake mp4 content")
        results.append(
            ChunkResult(
                chunk_id=spec.chunk_id,
                output_path=str(out),
                n_segments_processed=spec.n_payload_segments,
                success=True,
            )
        )

    # Delete a middle chunk's output.
    Path(results[1].output_path).unlink()

    expected_by_id = {
        c.chunk_id: c.expected_payload_duration_s for c in manifest.chunks
    }

    def probe(path: Path):
        cid = int(path.stem.rsplit("_", 1)[-1])
        return SimpleNamespace(duration_s=expected_by_id[cid])

    validation = validate_chunks(manifest, results, probe)
    assert validation.is_valid is False
    assert any("missing" in e.lower() for e in validation.errors)


@pytest.mark.polygon
@pytest.mark.slow
async def test_short_video_auto_reduces_workers(
    monkeypatch, chunked_test_video_90s: Path
) -> None:
    """A 90 s clip has 18 payload segments — requesting 4 workers with a 6-seg
    payload floor forces the planner to auto-reduce to 3 workers (6 segs per
    chunk, no remainder). The resulting signed video must still verify.

    This guards the planner's auto-reduction path: aggressive subdivision of
    short clips can drive enough per-chunk boundary errors to blow the Reed-
    Solomon budget (rs_n=18, k=10 → ≤4 symbol errors), so the planner is
    expected to land on a partition that keeps each chunk large enough.
    """
    _override_settings(
        monkeypatch,
        CHUNK_WORKERS=4,
        CHUNK_GUARD_SEGMENTS=1,
        CHUNK_MIN_PAYLOAD_SEGMENTS=6,
    )
    result = await _sign_and_verify(chunked_test_video_90s)
    assert result.verdict == Verdict.VERIFIED, (
        f"Expected VERIFIED but got {result.verdict} (reason={result.red_reason})"
    )
    assert result.wid_match is True
