"""
Smoke tests for sign_video() — video-only signing pipeline.

Uses a synthetic video generated by ffmpeg (testsrc, 120s at 25fps, 320×240).
"""
from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path

import pytest

from kernel_backend.core.domain.identity import Certificate
from kernel_backend.core.domain.watermark import SegmentFingerprint, VideoEntry
from kernel_backend.core.ports.registry import RegistryPort
from kernel_backend.core.ports.storage import StoragePort
from kernel_backend.core.services.crypto_service import derive_wid, generate_keypair
from kernel_backend.core.services.signing_service import sign_video
from kernel_backend.infrastructure.media.media_service import MediaService

PEPPER = b"test-pepper-bytes-padded-to-32b!"


@pytest.fixture(scope="module")
def synthetic_video(tmp_path_factory) -> Path:
    """120-second synthetic video (25fps, 320×240, no audio). ≥17 segments at 5s/seg."""
    tmp = tmp_path_factory.mktemp("video")
    out = tmp / "test.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", "testsrc=duration=120:size=320x240:rate=25",
            "-vcodec", "libx264",
            "-crf", "28",
            "-preset", "ultrafast",
            "-an",  # no audio
            str(out),
        ],
        check=True,
        capture_output=True,
    )
    return out


class FakeStorage(StoragePort):
    def __init__(self) -> None:
        self._store: dict[str, bytes] = {}

    async def put(self, key: str, data: bytes, content_type: str) -> None:
        self._store[key] = data

    async def get(self, key: str) -> bytes:
        return self._store[key]

    async def delete(self, key: str) -> None:
        self._store.pop(key, None)

    async def presigned_upload_url(self, key: str, expires_in: int) -> str:
        return f"fake://{key}"

    async def presigned_download_url(self, key: str, expires_in: int) -> str:
        return f"fake://{key}"


class FakeRegistry(RegistryPort):
    def __init__(self) -> None:
        self._videos: dict[str, VideoEntry] = {}
        self._segments: dict[str, list[SegmentFingerprint]] = {}

    async def save_video(self, entry: VideoEntry) -> None:
        self._videos[entry.content_id] = entry

    async def get_by_content_id(self, content_id: str) -> VideoEntry | None:
        return self._videos.get(content_id)

    async def get_valid_candidates(self) -> list[VideoEntry]:
        return [e for e in self._videos.values() if e.status == "VALID"]

    async def save_segments(
        self, content_id: str, segments: list[SegmentFingerprint], is_original: bool
    ) -> None:
        self._segments[content_id] = list(segments)

    async def match_fingerprints(
        self, hashes: list[str], max_hamming: int = 10
    ) -> list[VideoEntry]:
        return []


def _make_cert(public_key_pem: str) -> Certificate:
    return Certificate(
        author_id="test-author-id",
        name="Test Author",
        institution="Test Org",
        public_key_pem=public_key_pem,
        created_at="2026-01-01T00:00:00+00:00",
    )


async def test_sign_video_returns_valid_result(synthetic_video: Path) -> None:
    """sign_video returns a SigningResult with valid WID, signature, and UUID."""
    private_pem, public_pem = generate_keypair()
    cert = _make_cert(public_pem)

    result = await sign_video(
        media_path=synthetic_video,
        certificate=cert,
        private_key_pem=private_pem,
        storage=FakeStorage(),
        registry=FakeRegistry(),
        pepper=PEPPER,
        media=MediaService(),
    )

    assert len(result.wid.data) == 16
    assert len(result.signature) == 64
    parts = result.content_id.split("-")
    assert len(parts) == 5
    assert set(result.active_signals) == {
        "video_pilot", "video_wid", "video_fingerprint"
    }
    expected_hash = int.from_bytes(
        hashlib.sha256(result.content_id.encode()).digest()[:6], "big"
    )
    assert result.pilot_hash_48 == expected_hash


async def test_sign_video_raises_on_audio_only(tmp_path: Path) -> None:
    """Pass an audio-only file → ValueError."""
    audio = tmp_path / "audio.aac"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", "sine=frequency=200:duration=10",
            "-c:a", "aac",
            "-ar", "44100",
            str(audio),
        ],
        check=True,
        capture_output=True,
    )
    private_pem, public_pem = generate_keypair()
    cert = _make_cert(public_pem)

    with pytest.raises(ValueError, match="no video track"):
        await sign_video(
            media_path=audio,
            certificate=cert,
            private_key_pem=private_pem,
            storage=FakeStorage(),
            registry=FakeRegistry(),
            pepper=PEPPER,
            media=MediaService(),
        )


async def test_sign_video_raises_on_short_video(tmp_path: Path) -> None:
    """Video shorter than 85s (< 17 segments × 5s) → ValueError."""
    short = tmp_path / "short.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", "testsrc=duration=30:size=320x240:rate=25",
            "-vcodec", "libx264",
            "-crf", "28",
            "-preset", "ultrafast",
            "-an",
            str(short),
        ],
        check=True,
        capture_output=True,
    )
    private_pem, public_pem = generate_keypair()
    cert = _make_cert(public_pem)

    with pytest.raises(ValueError, match="Video is too short"):
        await sign_video(
            media_path=short,
            certificate=cert,
            private_key_pem=private_pem,
            storage=FakeStorage(),
            registry=FakeRegistry(),
            pepper=PEPPER,
            media=MediaService(),
        )


async def test_wid_derivation_deterministic(synthetic_video: Path) -> None:
    """WID is deterministically derived from signature and content_id."""
    private_pem, public_pem = generate_keypair()
    cert = _make_cert(public_pem)

    result = await sign_video(
        media_path=synthetic_video,
        certificate=cert,
        private_key_pem=private_pem,
        storage=FakeStorage(),
        registry=FakeRegistry(),
        pepper=PEPPER,
        media=MediaService(),
    )

    re_derived = derive_wid(result.signature, result.content_id)
    assert result.wid == re_derived
